# Site settings
title: Аниме топы
email: myanimetops@gmail.com
description: Составление топов для начинающих анимешников ^_^
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
# google_play: 'GDGX'
google_plus_com: '109485346959707049693'  # Community link
# google_plus_per: '+GDGManagua'  #Personal link
# facebook_app_id: 12345
lang: ru
# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]




# Build settings
markdown: kramdown

gems: [jekyll-paginate]
paginate: 15

gems:
  - jekyll-seo-tag
